### ISSUE TITLE
notification switch

### ISSUE THREAD

**Issue by thenameisluk** [dsheeler/gnome-shell-extensions-gravatar#1]
hi
so i really like the extension
but notification every time i log in into my account is kinda annoying
any chance to throw in a toggle to disable it?
thanks

**Comment by dsheeler** [comment]
Thanks for the input!  I'll make it an opt-in so that by default no notifications?

**Comment by dsheeler** [comment]
@LukIsHere: I just committed something to main that should do the trick if you could try it, that'd be great!

**Comment by thenameisluk** [comment]
i updated the extension
switched extension off and on, got notification (might have to look into that)
then went to settings toggles notification switch twice (so it was still off)
logged out and in, no notification
so yep it did the trick
thank you very much <3

**Comment by thenameisluk** [comment]
o yeah also you might also want to update the dconf thingy in the readme

**Comment by thenameisluk** [comment]
https://github.com/dsheeler/gnome-shell-extensions-gravatar/pull/2#issue-2293185343

should do the trick

**Comment by dsheeler** [comment]
@LukIsHere, Thanks!!!
